apiVersion: apps/v1
kind: Deployment
metadata:
  name: wine-ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wine-ml-app
  template:
    metadata:
      labels:
        app: wine-ml-app
    spec:
      containers:
      - name: wine-ml-app
        image: dock:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: wine-ml-service
spec:
  type: NodePort
  selector:
    app: wine-ml-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007  # Exposed on Minikube